export geographies, geographic_components, states, surv_dec, surv_acs, vars_acs, vars_dec

surv_dec = "2020/dec/dhc"
vars_dec = [
    # rurality
    "Rural" => "H2_003N"
    "Urban" => "H2_002N"
    "Urban + Rural" => "H2_001N"
]

surv_acs = "2023/acs/acs5"
vars_acs = [
    "TotalPopulation" => "B01001_001E"

    # Single-Parent Households
    "Male led Household with childeren" => "B11005_006E"
    "Female led Household with childeren" => "B11005_007E"
    # Nonfamilty household with child
    "NonFamily Household with childeren" => "B11005_008E"
    "Households with childeren" => "B11005_002E"

    # youth not in school
    "Male 16-19 no HS" => "B14005_012E"
    "Female 16-19 no HS" => "B14005_026E"
    "Female + Male 16-19" => "B14005_001E"

    # Pay Gap Sex
    "Male median earnings" => "B20001_002E"
    "Female median earnings" => "B20001_023E"

    # Pay Gap Race
    "White median earnings" => "B20017A_001E"
    "Black median earnings" => "B20017B_001E"

    # Housing Gap
    "Median House Price" => "B19013_001E"
    "Median Salary" => "B25077_001E"

    "Unemployment Rate" => "S2301_C04_001E"
    "Owner Occupied Housing" => "DP04_0046PE"

    #white collar jobs
    "White collar workers" => "C24060_002E"
    "Total workers" => "C24060_001E"

    # SNAP
    "Total Households" => "B22002_001E"
    "Total Households w/ SNAP" => "B22002_002E"
    "Total Households w/ SNAP + childeren" => "B22002_003E"
    "Total Households w/ SNAP + elders" => "B22001_003E"

    #tech
    "Households w/o Internet" => "B28002_013E"
    "Households w/ Broadband Internet" => "B28002_004E"
    "Households w/ Smartphone" => "B28010_005E"

    # char
    "Households w/o Car" => "DP04_0058E"
    "Households w/o Complete Plumbing" => "DP04_0073PE"
    "Households w/o Complete Kitchen" => "DP04_0074E"
    
    # transport
    "Over 60 min commuting" => "S0801_C01_045E"
    "WFH" => "S0801_C01_013E"
    "Public Transit to Work" => "S0801_C01_009E"
    "Walked to Work" => "S0801_C01_010E"
    "Biked to Work" => "S0801_C01_011E"
    "Total Workers" => "S0801_C01_001E"
];

geographies = Dict([
    ("us" => "010")
    ("region" => "020")
    ("division" => "030")
    ("state" => "040")
    ("county" => "050")
    ("county subdivision" => "060")
    ("subminor civil division" => "067")
    ("place/remainder (or part)" => "070")
    ("tract" => "140")
    ("block group" => "150")
    ("county (or part)" => "155")
    ("place" => "160")
    ("consolidated city" => "170")
    ("place (or part)" => "172")
    ("alaska native regional corporation" => "230")
    ("american indian area/alaska native area/hawaiian home land" => "250")
    ("tribal subdivision/remainder" => "251")
    ("american indian area/alaska native area (reservation or statistical entity only)" => "252")
    ("american indian area (off-reservation trust land only)/hawaiian home land" => "254")
    ("tribal census tract" => "256")
    ("tribal block group" => "258")
    ("state (or part)" => "260")
    #("place/remainder (or part)" => "269")
    #("county (or part)" => "270")
    ("american indian area/alaska native area/hawaiian home land (or part)" => "280")
    ("american indian area/alaska native area (reservation or statistical entity only) (or part)" => "283")
    ("american indian area (off-reservation trust land only)/hawaiian home land (or part)" => "286")
    #("state (or part)" => "290")
    #("tribal census tract (or part)" => "291")
    #("tribal census tract (or part)" => "292")
    #("tribal block group (or part)" => "293")
    #("tribal block group (or part)" => "294")
    ("metropolitan statistical area/micropolitan statistical area" => "310")
    #("state (or part)" => "311")
    ("principal city (or part)" => "312")
    #("county" => "313")
    ("metropolitan division" => "314")
    #("state (or part)" => "315")
    #("county" => "316")
    ("metropolitan statistical area/micropolitan statistical area (or part)" => "320")
    ("principal city (or part)" => "321")
    #("county" => "322")
    ("metropolitan division (or part)" => "323")
    #("county" => "324")
    ("combined statistical area" => "330")
    #("state (or part)" => "331")
    #("metropolitan statistical area/micropolitan statistical area" => "332")
    #("state (or part)" => "333")
    ("combined statistical area (or part)" => "340")
    #("metropolitan statistical area/micropolitan statistical area (or part)" => "341")
    ("urban area" => "400")
    #("state (or part)" => "410")
    #("county (or part)" => "430")
    ("congressional district" => "500")
    #("county (or part)" => "510")
    #("american indian area/alaska native area/hawaiian home land (or part)" => "550")
    ("state legislative district (upper chamber)" => "610")
    #("county (or part)" => "612")
    ("state legislative district (lower chamber)" => "620")
    #("county (or part)" => "622")
    ("public use microdata area" => "795")
    ("zip code tabulation area" => "860")
    ("school district (elementary)" => "950")
    ("school district (secondary)" => "960")
    ("school district (unified)" => "970")
]);

geographic_components = Dict([
    ("Not a geographic component" => "00")
    ("Urban" => "01")
    ("Urban - in urbanized area" => "04")
    ("Urban - in urbanized area of 5,000,000 or more population" => "05")
    ("Urban - in urbanized area of 2,500,000 to 4,999,999 population" => "06")
    ("Urban - in urbanized area of 1,000,000 to 2,499,999 population" => "07")
    ("Urban - in urbanized area of 500,000 to 999,999 population" => "08")
    ("Urban - in urbanized area of 250,000 to 499,999 population" => "09")
    ("Urban - in urbanized area of 100,000 to 249,999 population" => "10")
    ("Urban - in urbanized area of 50,000 to 99,999 population" => "11")
    ("Urban - in urban cluster" => "28")
    ("Urban - in urban cluster of 25,000 to 49,999 population" => "29")
    ("Urban - in urban cluster of 10,000 to 24,999 population" => "30")
    ("Urban - in urban cluster of 5,000 to 9,999 population" => "31")
    ("Urban - in urban cluster of 2,500 to 4,999 population" => "32")
    ("Rural" => "43")
    ("Rural - place" => "44")
    ("Rural - place of 2,500 or more population" => "45")
    ("Rural - place of 1,000 to 2,499 population" => "46")
    ("Rural - place of less than 1,000 population" => "47")
    ("Rural - not in place" => "48")
    ("Rural - farm" => "49")
    ("Urban portion of extended place" => "50")
    ("Rural portion of extended place" => "51")
    ("American Indian Reservation and Trust Land - Federal" => "89")
    ("American Indian Reservation and Trust Land - State" => "90")
    ("Oklahoma Tribal Statistical Area" => "91")
    ("Tribal Designated Statistical Area" => "92")
    ("Alaska Native Village Statistical Area" => "93")
    ("State Designated Tribal Statistical Area" => "94")
    ("Hawaiian Home Land" => "95")
    ("In metropolitan or micropolitan statistical area" => "A0")
    ("In metropolitan or micropolitan statistical area - in principal city" => "A1")
    ("In metropolitan or micropolitan statistical area - not in principal city" => "A2")
    ("In metropolitan or micropolitan statistical area - urban" => "A3")
    ("In metropolitan or micropolitan statistical area - urban - in urbanized area" => "A4")
    ("In metropolitan or micropolitan statistical area - urban - in urban cluster" => "A5")
    ("In metropolitan or micropolitan statistical area - rural" => "A6")
    ("In metropolitan or micropolitan statistical area of 5,000,000 or more population" => "A7")
    ("In metropolitan or micropolitan statistical area of 2,500,000 to 4,999,999 population" => "A8")
    ("In metropolitan or micropolitan statistical area of 1,000,000 to 2,499,999 population" => "A9")
    ("In metropolitan or micropolitan statistical area of 500,000 to 999,999 population" => "AA")
    ("In metropolitan or micropolitan statistical area of 250,000 to 499,999 population" => "AB")
    ("In metropolitan or micropolitan statistical area of 100,000 to 249,999 population" => "AC")
    ("In metropolitan or micropolitan statistical area of 50,000 to 99,999 population" => "AD")
    ("In metropolitan or micropolitan statistical area of 25,000 to 49,999 population" => "AE")
    ("In metropolitan or micropolitan statistical area of less than 25,000 population" => "AF")
    ("In metropolitan statistical area" => "C0")
    ("In metropolitan statistical area - in principal city" => "C1")
    ("In metropolitan statistical area - not in principal city" => "C2")
    ("In metropolitan statistical area - urban" => "C3")
    ("In metropolitan statistical area - urban - in urbanized area" => "C4")
    ("In metropolitan statistical area - urban - in urban cluster" => "C5")
    ("In metropolitan statistical area - rural" => "C6")
    ("In metropolitan statistical area of 5,000,000 or more population" => "C7")
    ("In metropolitan statistical area of 2,500,000 to 4,999,999 population" => "C8")
    ("In metropolitan statistical area of 1,000,000 to 2,499,999 population" => "C9")
    ("In metropolitan statistical area of 500,000 to 999,999 population" => "CA")
    ("In metropolitan statistical area of 250,000 to 499,999 population" => "CB")
    ("In metropolitan statistical area of 100,000 to 249,999 population" => "CC")
    ("In metropolitan statistical area of less than 100,000 population" => "CD")
    ("In metropolitan statistical area of 5,000,000 or more population - in principal city" => "CE")
    ("In metropolitan statistical area of 5,000,000 or more population - not in principal city" => "CF")
    ("In metropolitan statistical area of 2,500,000 to 4,999,999 population - in principal city" => "CG")
    ("In metropolitan statistical area of 2,500,000 to 4,999,999 population - not in principal city" => "CH")
    ("In metropolitan statistical area of 1,000,000 to 2,499,999 population - in principal city" => "CJ")
    ("In metropolitan statistical area of 1,000,000 to 2,499,999 population - not in principal city" => "CK")
    ("In metropolitan statistical area of 500,000 to 999,999 population - in principal city" => "CL")
    ("In metropolitan statistical area of 500,000 to 999,999 population - not in principal city" => "CM")
    ("In metropolitan statistical area of 250,000 to 499,999 population - in principal city" => "CN")
    ("In metropolitan statistical area of 250,000 to 499,999 population - not in principal city" => "CP")
    ("In metropolitan statistical area of 100,000 to 249,999 population - in principal city" => "CQ")
    ("In metropolitan statistical area of 100,000 to 249,999 population - not in principal city" => "CR")
    ("In metropolitan statistical area of less than 100,000 population - in principal city" => "CS")
    ("In metropolitan statistical area of less than 100,000 population - not in principal city" => "CT")
    ("In micropolitan statistical area" => "E0")
    ("In micropolitan statistical area - in principal city" => "E1")
    ("In micropolitan statistical area - not in principal city" => "E2")
    ("In micropolitan statistical area - urban" => "E3")
    ("In micropolitan statistical area - urban - in urbanized area" => "E4")
    ("In micropolitan statistical area - urban - in urban cluster" => "E5")
    ("In micropolitan statistical area - rural" => "E6")
    ("In micropolitan statistical area of 100,000 or more population" => "E7")
    ("In micropolitan statistical area of 50,000 to 99,999 population" => "E8")
    ("In micropolitan statistical area of 25,000 to 49,999 population" => "E9")
    ("In micropolitan statistical area of less than 25,000 population" => "EA")
    ("In micropolitan statistical area of 100,000 or more population - in principal city" => "EB")
    ("In micropolitan statistical area of 100,000 or more population - not in principal city" => "EC")
    ("In micropolitan statistical area of 50,000 to 99,999 population - in principal city" => "ED")
    ("In micropolitan statistical area of 50,000 to 99,999 population - not in principal city" => "EE")
    ("In micropolitan statistical area of 25,000 to 49,999 population - in principal city" => "EF")
    ("In micropolitan statistical area of 25,000 to 49,999 population - not in principal city" => "EG")
    ("In micropolitan statistical area of less than 25,000 population - in principal city" => "EH")
    ("In micropolitan statistical area of less than 25,000 population - not in principal city" => "EJ")
    ("Not in metropolitan or micropolitan statistical area" => "G0")
    ("Not in metropolitan or micropolitan statistical area - urban" => "G1")
    ("Not in metropolitan or micropolitan statistical area - urban - in urbanized area" => "G2")
    ("Not in metropolitan or micropolitan statistical area - urban - in urban cluster" => "G3")
    ("Not in metropolitan or micropolitan statistical area - rural" => "G4")
    ("Not in metropolitan statistical area" => "H0")
    ("Not in metropolitan statistical area - urban" => "H1")
    ("Not in metropolitan statistical area - urban - in urbanized area" => "H2")
    ("Not in metropolitan statistical area - urban - in urban cluster" => "H3")
    ("Not in metropolitan statistical area - rural" => "H4")
    ("In combined statistical area" => "J0")
    ("Not in combined statistical area" => "L0")
    ("In New England city and town area" => "M0")
    ("In New England city and town area - in principal city" => "M1")
    ("In New England city and town area - not in principal city" => "M2")
    ("In New England city and town area - urban" => "M3")
    ("In New England city and town area - urban - in urbanized area" => "M4")
    ("In New England city and town area - urban - in urban cluster" => "M5")
    ("In New England city and town area - rural" => "M6")
    ("In combined New England city and town area" => "P0")
]);

states = Dict([
    ("ALABAMA" => "01")
    ("ALASKA" => "02")
    ("AMERICAN SAMOA" => "60")
    ("ARIZONA" => "04")
    ("ARKANSAS" => "05")
    ("CALIFORNIA" => "06")
    ("COLORADO" => "08")
    ("CONNECTICUT" => "09")
    ("DELAWARE" => "10")
    ("DISTRICT OF COLUMBIA" => "11")
    ("FLORIDA" => "12")
    ("GEORGIA" => "13")
    ("GUAM" => "66")
    ("HAWAII" => "15")
    ("IDAHO" => "16")
    ("ILLINOIS" => "17")
    ("INDIANA" => "18")
    ("IOWA" => "19")
    ("KANSAS" => "20")
    ("KENTUCKY" => "21")
    ("LOUISIANA" => "22")
    ("MAINE" => "23")
    ("MARYLAND" => "24")
    ("MASSACHUSETTS" => "25")
    ("MICHIGAN" => "26")
    ("MINNESOTA" => "27")
    ("MISSISSIPPI" => "28")
    ("MISSOURI" => "29")
    ("MONTANA" => "30")
    ("NEBRASKA" => "31")
    ("NEVADA" => "32")
    ("NEW HAMPSHIRE" => "33")
    ("NEW JERSEY" => "34")
    ("NEW MEXICO" => "35")
    ("NEW YORK" => "36")
    ("NORTH CAROLINA" => "37")
    ("NORTH DAKOTA" => "38")
    ("NORTHERN MARIANA ISLANDS" => "69")
    ("OHIO" => "39")
    ("OKLAHOMA" => "40")
    ("OREGON" => "41")
    ("PENNSYLVANIA" => "42")
    ("Puerto Rico" => "72")
    ("RHODE ISLAND" => "44")
    ("SOUTH CAROLINA" => "45")
    ("SOUTH DAKOTA" => "46")
    ("TENNESSEE" => "47")
    ("TEXAS" => "48")
    ("UTAH" => "49")
    ("VERMONT" => "50")
    ("VIRGINIA" => "51")
    ("U.S. VIRGIN ISLANDS" => "78")
    ("WASHINGTON" => "53")
    ("WEST VIRGINIA" => "54")
    ("WISCONSIN" => "55")
    ("WYOMING" => "56")
    ("AL" => "01")
    ("AK" => "02")
    ("AS" => "60")
    ("AZ" => "04")
    ("AR" => "05")
    ("CA" => "06")
    ("CO" => "08")
    ("CT" => "09")
    ("DE" => "10")
    ("DC" => "11")
    ("FL" => "12")
    ("GA" => "13")
    ("GU" => "66")
    ("HI" => "15")
    ("ID" => "16")
    ("IL" => "17")
    ("IN" => "18")
    ("IA" => "19")
    ("KS" => "20")
    ("KY" => "21")
    ("LA" => "22")
    ("ME" => "23")
    ("MD" => "24")
    ("MA" => "25")
    ("MI" => "26")
    ("MN" => "27")
    ("MS" => "28")
    ("MO" => "29")
    ("MP" => "69")
    ("MT" => "30")
    ("NE" => "31")
    ("NV" => "32")
    ("NH" => "33")
    ("NJ" => "34")
    ("NM" => "35")
    ("NY" => "36")
    ("NC" => "37")
    ("ND" => "38")
    ("OH" => "39")
    ("OK" => "40")
    ("OR" => "41")
    ("PA" => "42")
    ("PR" => "72")
    ("RI" => "44")
    ("SC" => "45")
    ("SD" => "46")
    ("TN" => "47")
    ("TX" => "48")
    ("UT" => "49")
    ("VT" => "50")
    ("VA" => "51")
    ("VI" => "78")
    ("WA" => "53")
    ("WV" => "54")
    ("WI" => "55")
    ("WY" => "56")
]);
